"""baseline schema

Revision ID: ebe17429fa03
Revises: 
Create Date: 2026-07-12 19:48:53.362546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe17429fa03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcontractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('coi_expiration', sa.Date(), nullable=True),
    sa.Column('last_reminder_sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcontractor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcontractor_coi_expiration'), ['coi_expiration'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontractor_user_id'), ['user_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('ai_status', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_extracted_data', sa.JSON(), nullable=True),
    sa.Column('ai_compliance_result', sa.JSON(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sub_id'], ['subcontractor.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_ai_status'), ['ai_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sub_id'), ['sub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('project_subcontractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subcontractor_id', sa.Integer(), nullable=False),
    sa.Column('approved_for_project', sa.Boolean(), nullable=True),
    sa.Column('coverage_limit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'subcontractor_id', name='unique_project_sub')
    )
    with op.batch_alter_table('project_subcontractor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_subcontractor_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_subcontractor_subcontractor_id'), ['subcontractor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_subcontractor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_subcontractor_subcontractor_id'))
        batch_op.drop_index(batch_op.f('ix_project_subcontractor_project_id'))

    op.drop_table('project_subcontractor')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_document_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_document_sub_id'))
        batch_op.drop_index(batch_op.f('ix_document_project_id'))
        batch_op.drop_index(batch_op.f('ix_document_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_ai_status'))

    op.drop_table('document')
    with op.batch_alter_table('subcontractor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontractor_user_id'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_email'))
        batch_op.drop_index(batch_op.f('ix_subcontractor_coi_expiration'))

    op.drop_table('subcontractor')
    op.drop_table('project')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
